# .github/workflows/block-no-merge-label.yml
name: Block PRs with "no-merge" label

on:
  pull_request:
    types: [labeled, unlabeled, synchronize, opened, reopened]

jobs:
  check-label:
    runs-on: ubuntu-latest
    steps:
      - name: Check for "no-merge" label
        uses: actions/github-script@v7
        with:
          script: |
            const labels = context.payload.pull_request.labels.map(label => label.name);
            if (labels.includes("NO-MERGE")) {
              core.setFailed("This pull request has a NO-MERGE label and cannot be merged.");
            }
